export interface ExperienceStory {
  slug: string
  title: string
  program: string
  period: string
  story: string[]
  highlights: string[]
}

export const experiences: ExperienceStory[] = [
  {
    slug: 'data-analyst-iv',
    title: 'Data Analyst IV — Technical Lead',
    program: 'F-35 · Supply Optimization & Logistics',
    period: '2026 – Present',
    story: [
      'After four years of progressively building expertise across multiple F-35 domains, I stepped into the Technical Lead role for Supply Optimization and Logistics Modeling — the most complex sustainment analytics challenge on the program.',
      'My first priority was establishing a coherent technical vision for the team. We had capable analysts working in silos, each solving fragments of a much larger puzzle. I mapped out how our individual models could feed into a unified sustainment intelligence platform and began directing strategy accordingly, while also bringing new analysts up to speed faster through structured onboarding.',
      'The most technically ambitious work of this role has been developing predictive models that use actual F-35 sensor telemetry and flight operational data to anticipate maintenance event due dates before they happen. Traditional sustainment planning reacts to maintenance — we are building the capability to get ahead of it, aligning spares procurement with predicted demand rather than historical averages.',
      'Alongside forecasting, I am architecting automated data workflows to replace the manual reporting processes the team has relied on for years. These workflows standardize data ingestion, validation, and output — eliminating the version-control chaos that comes with spreadsheet-driven reporting and giving leadership a reliable, consistent view of the sustainment enterprise.',
      'The stakes in this role are real. Every improvement in forecast accuracy translates to aircraft spending more time flying and less time waiting on parts. That connection between the work we do in the data and the warfighter\'s ability to execute their mission is what drives the work.',
    ],
    highlights: [
      'Directing technical strategy for sustainment analytics across the F-35 global fleet',
      'Predictive modeling using sensor telemetry to anticipate maintenance event due dates',
      'Architecting automated pipelines to replace manual enterprise reporting',
      'Onboarding and mentoring new analysts into complex sustainment domains',
    ],
  },
  {
    slug: 'operations-analyst-iii',
    title: 'Operations Analyst III',
    program: 'F-35 · Supply Optimization & Logistics',
    period: '2024 – 2026',
    story: [
      'Moving into Supply Optimization and Logistics represented a major shift — from quality metrics on the production floor to the global supply chain that keeps F-35 fleets flying. The program spans dozens of international partner nations, each with unique operational patterns, basing configurations, and demand profiles.',
      'The centerpiece of my work in this role was an inventory optimization algorithm I developed to identify part surpluses and deficiencies across the enterprise. The challenge was significant: with thousands of line replaceable units distributed across global storage sites and in-transit pipelines, finding the right balance between over-procurement (which ties up capital) and under-procurement (which grounds aircraft) is genuinely difficult. My algorithm processed inventory positions, historical demand, and redistribution logistics to surface actionable rebalancing recommendations.',
      'The cost avoidance generated by this work was meaningful at the program level. Parts that were sitting idle in one location could be redistributed to meet active demand elsewhere, reducing emergency buys and keeping aircraft available for their missions.',
      'I also built out the demand-forecasting side of the equation, using flight-hour data and deployment configuration records to project future part requirements by location. If a partner nation is planning an operational surge, their part consumption profile changes — our forecasts needed to reflect that to keep the supply chain ahead of demand.',
      'To make this work sustainable beyond my own involvement, I documented analytical workflows and SOPs on Confluence, giving the team a shared foundation that new analysts could pick up without starting from scratch.',
    ],
    highlights: [
      'Inventory optimization algorithm identifying surpluses and deficiencies across global F-35 supply chain',
      'Significant cost reduction while maintaining full operational availability for all partner nations',
      'Flight-hour and deployment-driven demand forecasting aligned to warfighter mission needs',
      'Confluence SOPs standardizing analytical workflows across the team',
    ],
  },
  {
    slug: 'systems-engineer-iii',
    title: 'Systems Engineer III',
    program: 'F-16 · Diminished Manufacturing Sources',
    period: '2023 – 2024',
    story: [
      'Diminished Manufacturing Sources — DMS — is one of the quieter but more consequential challenges in defense sustainment. When the original manufacturers of critical aircraft components exit the market, cease production, or lose key suppliers of their own, the program is left with a gap that can ripple through global production and maintenance schedules if not addressed proactively.',
      'My role was to manage that risk for the F-16 program. The work required me to maintain a constant awareness of the hardware landscape: which components were showing signs of supply fragility, which manufacturers were consolidating or shutting lines down, and where production backlogs were emerging upstream.',
      'Rather than waiting for a shortage to surface in the supply chain, I built a proactive identification process that flagged risks early — giving the engineering and procurement teams enough runway to evaluate alternatives before a crisis. This meant close collaboration with cross-functional partners: sourcing teams, design engineers, and in some cases the original equipment manufacturers themselves.',
      'When a gap was identified, the work shifted to solution engineering. That could mean qualifying an alternate component that meets the same form, fit, and function requirements, working with suppliers to restart dormant production lines, or coordinating lifetime buys to bridge the gap while a longer-term solution was developed.',
      'The F-16 remains one of the most widely operated fighters in the world, with partner nations across every major region. Keeping that supply chain intact — even for aging hardware — is an active, technical challenge that this role gave me deep exposure to.',
    ],
    highlights: [
      'Proactive DMS risk identification across F-16 hardware landscape',
      'Cross-functional collaboration with sourcing, design engineering, and OEM partners',
      'Alternative component qualification and supply disruption mitigation',
      'Sustained global F-16 production and sustainment pipeline continuity',
    ],
  },
  {
    slug: 'data-analyst-ii',
    title: 'Data Analyst II',
    program: 'F-35 · Quality & Mission Success',
    period: '2022 – 2023',
    story: [
      'This was where my identity as a data analyst really took shape. The Quality & Mission Success team sits at the intersection of production and delivery — tracking defects, inspection performance, and the metrics that determine whether a delivered aircraft meets the standards the warfighter needs.',
      'The production environment generates enormous amounts of data. Every defect gets logged. Every inspection hour gets recorded. Every build area has its own failure history. The challenge is not collecting data — it is turning that data into something leadership can actually act on.',
      'I built interactive Tableau dashboards that let production and quality leadership drill into defect trends by build area, failure mode, and time period. Instead of weekly reports that were already stale by the time they were read, leadership had live views of what was breaking, where it was breaking, and how often. That shift from reactive to real-time awareness changed how conversations about quality improvement happened.',
      'I also developed performance monitoring tools that connected inspection hours to actual output — answering the question of whether the labor we were spending on inspection was proportional to what was coming off the line. Those tools fed resource allocation decisions that made the inspection process more efficient without sacrificing coverage.',
      'Beyond F-35, I contributed analytics work to C-130 production lines as well, expanding my exposure to how data-driven quality management applies across different program scales and operational contexts.',
      'Python and SQL were the backbone of the analysis work. Alteryx handled the ETL pipelines that fed the dashboards. That stack — extract, transform, visualize — became the foundation I have continued building on through every subsequent role.',
    ],
    highlights: [
      'Interactive Tableau dashboards enabling real-time defect tracking by build area',
      'Performance monitoring connecting inspection labor to production output',
      'End-to-end data pipelines using Python, SQL, and Alteryx across F-35 and C-130 programs',
      'Shifted quality reporting from static weekly reviews to live operational visibility',
    ],
  },
  {
    slug: 'project-management-operations-i',
    title: 'Project Management & Operations I',
    program: 'F-16 · Upgrades & Modifications',
    period: '2021 – 2022',
    story: [
      'My first role at Lockheed Martin dropped me into the F-16 Upgrades and Modifications portfolio — a fast-moving environment where contracts are complex, deadlines are real, and project performance has to be tracked rigorously to keep programs on budget and on schedule.',
      'Earned Value Management System reporting — EVMS — is the formal method the defense industry uses to measure project performance. It tracks how much work was planned, how much was actually accomplished, and how much it cost, generating metrics that program leadership and government customers use to assess program health. Learning this discipline early was foundational.',
      'The manual reporting process that existed when I arrived was labor-intensive and error-prone. I automated large portions of it, building tools that pulled performance data from source systems, calculated the key EVMS metrics, and formatted the outputs in a way that was ready for customer delivery. What had taken hours of analyst time each reporting cycle was reduced significantly.',
      'I also supported contract bidding work within the AMMM portfolio, developing the analytical tools used to assess cost and schedule assumptions during the proposal process. That exposure to the front end of the business — how programs are priced and structured before they begin — gave me a perspective on project economics that has been useful throughout my career.',
      'Starting here gave me grounding in how large defense programs are managed, governed, and measured. That foundation made everything that came after — the data work, the systems engineering, the optimization modeling — easier to connect to real program outcomes.',
    ],
    highlights: [
      'Automated EVMS reporting tools replacing manual tracking processes',
      'Contract bidding support and cost/schedule analysis for F-16 and AMMM portfolios',
      'Foundational exposure to defense program management and performance measurement',
      'Early career grounding in how large programs are governed and evaluated',
    ],
  },
]

export function getExperience(slug: string): ExperienceStory | undefined {
  return experiences.find((e) => e.slug === slug)
}
